### ISSUE TITLE
Push permissions

### ISSUE THREAD

**Issue by gstavrinos** [sokb/image_segmentation_node#1]
Hey Socrates, apparently git lfs does not work on forks, so I will have to push on your repository. Please add me as a collaborator so that I can push some cool rosbags, and then remove me again!

Thanks,

G

**Comment by sokb** [comment]
Access granted!

**Comment by gstavrinos** [comment]
Thanks! I just pushed some rosbags. Remember that you will have to use git-lfs to use them.  You can now remove me from the collaborators if you want.

Closing the issue.
